# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: ef4a397f916211b4a39ccf9d3d9cbb6562157251 # frozen: v3.9.9
    hooks:
      - id: prettier
        args: [--no-semi]
