export const START_LOADING_ACCOUNT_TRANSACTIONS = 'START_LOADING_ACCOUNT_TRANSACTIONS';
export const FINISHED_LOADING_ACCOUNT_TRANSACTIONS = 'FINISHED_LOADING_ACCOUNT_TRANSACTIONS';
export const ACCOUNT_TRANSACTIONS_LOAD_SUCCESS = 'ACCOUNT_TRANSACTIONS_LOAD_SUCCESS';
export const ACCOUNT_TRANSACTIONS_LOAD_FAIL = 'ACCOUNT_TRANSACTIONS_LOAD_FAIL';
