export const START_LOADING_PAYSTRING = 'START_LOADING_PAYSTRING';
export const FINISHED_LOADING_PAYSTRING = 'FINISHED_LOADING_PAYSTRING';
export const PAYSTRING_LOAD_SUCCESS = 'PAYSTRING_LOAD_SUCCESS';
export const RESOLVE_PAYSTRING_LOAD_FAIL = 'RESOLVE_PAYSTRING_LOAD_FAIL';
