export const START_LOADING_VALIDATOR = 'START_LOADING_VALIDATOR'
export const FINISH_LOADING_VALIDATOR = 'FINISH_LOADING_VALIDATOR'
export const LOADING_VALIDATOR_SUCCESS = 'LOADING_VALIDATOR_SUCCESS'
export const LOADING_VALIDATOR_FAIL = 'LOADING_VALIDATOR_FAIL'
