export const START_LOADING_FULL_LEDGER = 'START_LOADING_FULL_LEDGER';
export const FINISH_LOADING_FULL_LEDGER = 'FINISH_LOADING_FULL_LEDGER';
export const LOADING_FULL_LEDGER_SUCCESS = 'LOADING_FULL_LEDGER_SUCCESS';
export const LOADING_FULL_LEDGER_FAIL = 'LOADING_FULL_LEDGER_FAIL';
