export const START_LOADING_TRANSACTION = 'START_LOADING_TRANSACTION'
export const FINISH_LOADING_TRANSACTION = 'FINISH_LOADING_TRANSACTION'
export const LOADING_TRANSACTION_SUCCESS = 'LOADING_TRANSACTION_SUCCESS'
export const LOADING_TRANSACTION_FAIL = 'LOADING_TRANSACTION_FAIL'
