export const START_LOADING_ACCOUNT_NFTS = 'START_LOADING_ACCOUNT_NFTS';
export const ACCOUNT_NFTS_LOAD_SUCCESS = 'ACCOUNT_NFTS_LOAD_SUCCESS';
export const ACCOUNT_NFTS_LOAD_FAIL = 'ACCOUNT_NFTS_LOAD_FAIL';
